In [1]:
import geopandas as gpd
from sklearn.model_selection import train_test_split

In [2]:
df = gpd.read_file('../../QGIS/aglomerados_subnormais/final_shapefiles/sp/shapefile_sampled_data.shp')
df

,fid,CD_MUN,NM_MUN,SIGLA,AREA_KM2,id,left,top,right,bottom,...,AP3_NO_BAI,Shape_Leng,Shape_Area,deprived_a,_count,_sum,_mean,area_total,class,geometry
0,4450.0,3550308,São Paulo,SP,1521.202,4450.0,313921.320095,7.408279e+06,314021.320095,7.408179e+06,...,ANHANGUERA,0.02487,0.000011,7151.248741,0.050887,0.534391,10.501437,9999.450,1,"POLYGON ((-46.82029 -23.4248, -46.8203 -23.425..."
1,4451.0,3550308,São Paulo,SP,1521.202,4451.0,313921.320095,7.408179e+06,314021.320095,7.408079e+06,...,ANHANGUERA,0.02487,0.000011,7923.951010,0.050888,0.534394,10.501437,9999.450,1,"POLYGON ((-46.8203 -23.42571, -46.82031 -23.42..."
2,5178.0,3550308,São Paulo,SP,1521.202,5178.0,314021.320095,7.408279e+06,314121.320095,7.408179e+06,...,ANHANGUERA,0.02487,0.000011,9999.459049,0.050887,0.534391,10.501437,9999.459,1,"POLYGON ((-46.81931 -23.42481, -46.81932 -23.4..."
3,5179.0,3550308,São Paulo,SP,1521.202,5179.0,314021.320095,7.408179e+06,314121.320095,7.408079e+06,...,ANHANGUERA,0.02487,0.000011,8237.508823,0.050888,0.534395,10.501437,9999.459,1,"POLYGON ((-46.81932 -23.42572, -46.81934 -23.4..."
4,5180.0,3550308,São Paulo,SP,1521.202,5180.0,314021.320095,7.408079e+06,314121.320095,7.407979e+06,...,ANHANGUERA,0.02487,0.000011,8190.512394,0.050888,0.278058,5.464097,9999.459,1,"POLYGON ((-46.81934 -23.42662, -46.81935 -23.4..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7513,51904.0,3550308,São Paulo,SP,1521.202,51904.0,320421.320095,7.394879e+06,320521.320095,7.394779e+06,...,None,NaN,NaN,NaN,0.050936,3.273031,64.257339,10000.037,0,"POLYGON ((-46.7583 -23.54651, -46.75831 -23.54..."
7514,167618.0,3550308,São Paulo,SP,1521.202,167618.0,336321.320095,7.398679e+06,336421.320095,7.398579e+06,...,None,NaN,NaN,NaN,0.050931,3.449973,67.738403,10001.385,0,"POLYGON ((-46.60216 -23.51389, -46.60217 -23.5..."
7515,273188.0,3550308,São Paulo,SP,1521.202,273188.0,350821.320095,7.397679e+06,350921.320095,7.397579e+06,...,None,NaN,NaN,NaN,0.050940,3.052912,59.930961,10002.506,0,"POLYGON ((-46.46028 -23.52431, -46.46029 -23.5..."
7516,21937.0,3550308,São Paulo,SP,1521.202,21937.0,316321.320095,7.406779e+06,316421.320095,7.406679e+06,...,None,NaN,NaN,NaN,0.050894,1.175429,23.095774,9999.669,0,"POLYGON ((-46.79699 -23.43862, -46.797 -23.439..."
7517,74036.0,3550308,São Paulo,SP,1521.202,74036.0,323421.320095,7.365679e+06,323521.320095,7.365579e+06,...,None,NaN,NaN,NaN,0.051038,0.714301,13.995389,10000.301,0,"POLYGON ((-46.73239 -23.81048, -46.7324 -23.81..."

In [3]:
_, stratified_sample = train_test_split(df, test_size=3000, stratify=df[['class']])
stratified_sample

,fid,CD_MUN,NM_MUN,SIGLA,AREA_KM2,id,left,top,right,bottom,...,AP3_NO_BAI,Shape_Leng,Shape_Area,deprived_a,_count,_sum,_mean,area_total,class,geometry
2645,268202.0,3550308,São Paulo,SP,1521.202,268202.0,350121.320095,7.386679e+06,350221.320095,7.386579e+06,...,JD RIO CLARO,0.011022,0.000003,6921.117351,0.050978,2.632441,51.638909,10002.454,1,"POLYGON ((-46.46824 -23.62358, -46.46825 -23.6..."
3686,329293.0,3550308,São Paulo,SP,1521.202,329293.0,358521.320095,7.392779e+06,358621.320095,7.392679e+06,...,COHAB JUSCELINO,0.053847,0.000062,7173.175681,0.050960,0.658605,12.923883,10003.059,1,"POLYGON ((-46.38534 -23.56925, -46.38535 -23.5..."
5606,185794.0,3550308,São Paulo,SP,1521.202,185794.0,338821.320095,7.401079e+06,338921.320095,7.400979e+06,...,None,NaN,NaN,NaN,0.050924,3.201772,62.873844,10001.586,0,"POLYGON ((-46.57743 -23.49247, -46.57744 -23.4..."
3369,309656.0,3550308,São Paulo,SP,1521.202,309656.0,355821.320095,7.390879e+06,355921.320095,7.390779e+06,...,CIDADE TIRADENTES,0.014868,0.000009,9153.793496,0.050966,3.084502,60.521057,10002.869,1,"POLYGON ((-46.41197 -23.58617, -46.41198 -23.5..."
5126,148732.0,3550308,São Paulo,SP,1521.202,148732.0,333721.320095,7.394479e+06,333821.320095,7.394379e+06,...,None,NaN,NaN,NaN,0.050944,4.535115,89.021582,10001.173,0,"POLYGON ((-46.62809 -23.55154, -46.6281 -23.55..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3629,326406.0,3550308,São Paulo,SP,1521.202,326406.0,358121.320095,7.390279e+06,358221.320095,7.390179e+06,...,CIDADE TIRADENTES,0.015589,0.000008,10003.031136,0.050969,4.138297,81.192874,10003.031,1,"POLYGON ((-46.38949 -23.59179, -46.3895 -23.59..."
4737,275419.0,3550308,São Paulo,SP,1521.202,275419.0,351121.320095,7.392979e+06,351221.320095,7.392879e+06,...,None,NaN,NaN,NaN,0.050957,2.228609,43.735378,10002.528,0,"POLYGON ((-46.45781 -23.56678, -46.45782 -23.5..."
5906,317614.0,3550308,São Paulo,SP,1521.202,317614.0,356921.320095,7.395879e+06,357021.320095,7.395779e+06,...,None,NaN,NaN,NaN,0.050949,2.264630,44.448887,10002.947,0,"POLYGON ((-46.40072 -23.54112, -46.40073 -23.5..."
4574,59382.0,3550308,São Paulo,SP,1521.202,59382.0,321421.320095,7.375079e+06,321521.320095,7.374979e+06,...,None,NaN,NaN,NaN,0.051005,0.527100,10.334320,10000.126,0,"POLYGON ((-46.75088 -23.72539, -46.75089 -23.7..."
6723,87887.0,3550308,São Paulo,SP,1521.202,87887.0,325321.320095,7.363779e+06,325421.320095,7.363679e+06,...,None,NaN,NaN,NaN,0.051046,0.893208,17.498144,10000.466,0,"POLYGON ((-46.71397 -23.82784, -46.71398 -23.8..."

In [5]:
ids = stratified_sample['fid'].astype(int).tolist()
print(len(ids))

3000

In [10]:
# filter images based on ids from dataset/old/GMAPS_RGB_SP_2024 to dataset/GMAPS_RGB_SP_2024

import os
import shutil

src = '../dataset/old/GMAPS_RGB_SP_2024'
dst = '../dataset/GMAPS_RGB_SP_2024'

for idx, id in enumerate(ids):
    # print(idx)
    achou = False
    for filename in os.listdir(src):
        if filename.startswith(str(id)):
            shutil.copy(os.path.join(src, filename), dst)
            # print(f'Copied {filename} to {dst}')
            achou = True
            break
        else:
            # print(f'Image for id {id} not found')
            continue
    if not achou:
        print(f'Image for id {id} not found')